// demo_frame_rom.svh — generated by tools/gen_demo_frame.py; do not edit.
// One valid MDM-16 QUOTE frame (ASK 0x0001 @ 99.9500, qty 250, seq 0x42),
// padded to the 60-byte Ethernet minimum.

localparam int unsigned DEMO_LEN = 60;

function automatic logic [7:0] demo_rom(input logic [5:0] i);
    case (i)
        6'd0: demo_rom = 8'h02;
        6'd1: demo_rom = 8'h00;
        6'd2: demo_rom = 8'h00;
        6'd3: demo_rom = 8'hC0;
        6'd4: demo_rom = 8'hFF;
        6'd5: demo_rom = 8'hEE;
        6'd6: demo_rom = 8'h02;
        6'd7: demo_rom = 8'h00;
        6'd8: demo_rom = 8'h00;
        6'd9: demo_rom = 8'hAA;
        6'd10: demo_rom = 8'hBB;
        6'd11: demo_rom = 8'hCC;
        6'd12: demo_rom = 8'h08;
        6'd13: demo_rom = 8'h00;
        6'd14: demo_rom = 8'h45;
        6'd15: demo_rom = 8'h00;
        6'd16: demo_rom = 8'h00;
        6'd17: demo_rom = 8'h2C;
        6'd18: demo_rom = 8'h00;
        6'd19: demo_rom = 8'h01;
        6'd20: demo_rom = 8'h00;
        6'd21: demo_rom = 8'h00;
        6'd22: demo_rom = 8'h40;
        6'd23: demo_rom = 8'h11;
        6'd24: demo_rom = 8'h66;
        6'd25: demo_rom = 8'hBE;
        6'd26: demo_rom = 8'h0A;
        6'd27: demo_rom = 8'h00;
        6'd28: demo_rom = 8'h00;
        6'd29: demo_rom = 8'h02;
        6'd30: demo_rom = 8'h0A;
        6'd31: demo_rom = 8'h00;
        6'd32: demo_rom = 8'h00;
        6'd33: demo_rom = 8'h01;
        6'd34: demo_rom = 8'hC7;
        6'd35: demo_rom = 8'h38;
        6'd36: demo_rom = 8'hB7;
        6'd37: demo_rom = 8'hFC;
        6'd38: demo_rom = 8'h00;
        6'd39: demo_rom = 8'h18;
        6'd40: demo_rom = 8'h84;
        6'd41: demo_rom = 8'hDC;
        6'd42: demo_rom = 8'hA5;
        6'd43: demo_rom = 8'h11;
        6'd44: demo_rom = 8'h00;
        6'd45: demo_rom = 8'h01;
        6'd46: demo_rom = 8'h01;
        6'd47: demo_rom = 8'h00;
        6'd48: demo_rom = 8'h00;
        6'd49: demo_rom = 8'h0F;
        6'd50: demo_rom = 8'h40;
        6'd51: demo_rom = 8'h4C;
        6'd52: demo_rom = 8'h00;
        6'd53: demo_rom = 8'hFA;
        6'd54: demo_rom = 8'h00;
        6'd55: demo_rom = 8'h00;
        6'd56: demo_rom = 8'h00;
        6'd57: demo_rom = 8'h42;
        6'd58: demo_rom = 8'h00;
        6'd59: demo_rom = 8'h00;
        default: demo_rom = 8'h00;
    endcase
endfunction
