#!/usr/bin/env python3
"""Generate rtl/demo_frame_rom.svh — the canned frame for the board demo.

Builds one valid Ethernet/IPv4/UDP frame carrying a single MDM-16 QUOTE that
crosses the demo BUY threshold, using scapy (so the IP checksum and lengths
come from an implementation independent of both the RTL and the testbench
golden model), then emits it as a SystemVerilog localparam ROM.

Run from the repo root:  python3 tools/gen_demo_frame.py
"""

import pathlib
import struct

from scapy.all import Ether, IP, UDP, raw  # type: ignore

MY_MAC = "02:00:00:c0:ff:ee"
SRC_MAC = "02:00:00:aa:bb:cc"
LISTEN_PORT = 47100

# MDM-16 QUOTE: symbol 0x0001, ASK @ 99.9500 (ticks of 1e-4), qty 250, seq 0x42.
# price 999_500 < BUY_THRESH 1_000_000  =>  the trigger fires BUY.
MAGIC = 0xA5
VER_TYPE = 0x11  # version 1, type 1 (QUOTE)
SYMBOL = 0x0001
SIDE_ASK = 0x01
PRICE = 999_500
QTY = 250        # above MAX_QTY=100: the emitted record shows the risk cap
SEQ = 0x00000042

payload = struct.pack(
    ">BBHBBIHI", MAGIC, VER_TYPE, SYMBOL, SIDE_ASK, 0x00, PRICE, QTY, SEQ
)
assert len(payload) == 16

frame = raw(
    Ether(dst=MY_MAC, src=SRC_MAC)
    / IP(src="10.0.0.2", dst="10.0.0.1", flags=0)
    / UDP(sport=51000, dport=LISTEN_PORT)
    / payload
)
# pad to the 60-byte Ethernet minimum (FCS excluded); the parsers ignore
# bytes past the declared UDP length
frame = frame.ljust(60, b"\x00")

out = pathlib.Path(__file__).resolve().parent.parent / "rtl" / "demo_frame_rom.svh"
# Emitted as a case-statement function rather than an unpacked-array
# localparam: Icarus Verilog does not support unpacked array parameters,
# and a function ROM synthesizes to the same LUTs in Vivado.
lines = [
    "// demo_frame_rom.svh — generated by tools/gen_demo_frame.py; do not edit.",
    "// One valid MDM-16 QUOTE frame (ASK 0x0001 @ 99.9500, qty 250, seq 0x42),",
    "// padded to the 60-byte Ethernet minimum.",
    "",
    f"localparam int unsigned DEMO_LEN = {len(frame)};",
    "",
    "function automatic logic [7:0] demo_rom(input logic [5:0] i);",
    "    case (i)",
]
for i, b in enumerate(frame):
    lines.append(f"        6'd{i}: demo_rom = 8'h{b:02X};")
lines += [
    "        default: demo_rom = 8'h00;",
    "    endcase",
    "endfunction",
    "",
]
out.write_text("\n".join(lines))
print(f"wrote {out} ({len(frame)} bytes)")
